"""
LAYER 5 -- REPORT GENERATION

Per the architecture: "PDF export (WeasyPrint/ReportLab) + editable DOCX
export." We use ReportLab (pure Python, no system-level cairo/pango
dependency like WeasyPrint needs), which keeps the backend container
simple to build and deploy.
"""

import io
import base64
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.models import Scan

STATUS_COLORS = {
    "COMPLIANT": colors.HexColor("#2F7A45"),
    "NON_COMPLIANT": colors.HexColor("#B23A2F"),
    "NEEDS_REVIEW": colors.HexColor("#B9791D"),
}


def generate_report_pdf(scan: Scan) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=20)
    story = []

    story.append(Paragraph("PackSure Compliance Report", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011 — Automated Verification", styles["Normal"]))
    story.append(Spacer(1, 10))

    status_color = STATUS_COLORS.get(scan.overall_status, colors.grey)
    status_table = Table(
        [[f"{scan.overall_status.replace('_', ' ')} — Score {scan.compliance_score}/100"]],
        colWidths=[170 * mm],
    )
    status_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.Color(status_color.red, status_color.green, status_color.blue, alpha=0.15)),
        ("TEXTCOLOR", (0, 0), (-1, -1), status_color),
        ("FONTSIZE", (0, 0), (-1, -1), 14),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(status_table)
    story.append(Spacer(1, 14))

    meta = [
        ["Product", scan.product_label],
        ["Scan ID", scan.id],
        ["Scanned At", scan.created_at.strftime("%d %b %Y, %H:%M")],
        ["PDP Detection Method", scan.pdp_detection_method or "—"],
        ["Calibration Source", scan.calibration_source or "None (font-size checks unverifiable)"],
    ]
    meta_table = Table(meta, colWidths=[50 * mm, 120 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 14))

    if scan.image_data_url and "," in scan.image_data_url:
        try:
            img_bytes = base64.b64decode(scan.image_data_url.split(",", 1)[1])
            img_buf = io.BytesIO(img_bytes)
            story.append(RLImage(img_buf, width=70 * mm, height=95 * mm))
            story.append(Spacer(1, 10))
        except Exception:
            pass

    story.append(Paragraph("Mandatory Field Checklist", styles["Heading2"]))
    field_rows = [["Field", "Extracted Value", "Status", "Font (mm)"]]
    for f in scan.fields:
        font_str = f"{f.font_height_mm:.2f} / min {f.min_required_mm:.1f}" if f.font_height_mm else "—"
        field_rows.append([f.field_key, (f.extracted_text or "— not found —")[:40], f.status, font_str])
    field_table = Table(field_rows, colWidths=[40 * mm, 65 * mm, 25 * mm, 40 * mm])
    field_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFEFEF")),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(field_table)
    story.append(Spacer(1, 14))

    story.append(Paragraph(f"Violations ({len(scan.violations)})", styles["Heading2"]))
    if not scan.violations:
        story.append(Paragraph("No violations detected.", styles["Normal"]))
    else:
        for v in scan.violations:
            story.append(Paragraph(f"<b>{v.severity} — {v.rule_code}</b>: {v.description}", styles["Normal"]))
            story.append(Paragraph(f"<font size=8 color=grey>Reference: {v.citation}</font>", styles["Normal"]))
            story.append(Spacer(1, 6))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<font size=8 color=grey>Generated by PackSure — an automated pre-screening tool built for SIH26034. "
        "This report supports, but does not replace, review by an authorised Legal Metrology officer.</font>",
        styles["Normal"],
    ))

    doc.build(story)
    return buf.getvalue()
